name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.201.166.239
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/testing
            git pull origin main
            npm install
            pm2 restart node-app --update-env
            echo "Fetching latest PM2 logs..."
            pm2 logs --lines 5
